services:
  db:
    image: postgres:16
    container_name: crunchcart_db
    environment:
      POSTGRES_DB: crunchcart
      POSTGRES_USER: crunchcart
      POSTGRES_PASSWORD: crunchcart
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: