spring:
  application:
    name: Crunchcart
  datasource:
    url: jdbc:postgresql://localhost:5432/crunchcart
    username: crunchcart
    password: crunchcart
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true

  flyway:
    enabled: true
    locations: classpath:db/migration
  server:
    port: 8080

